# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               blog
tagline:             Ivan Jiang
url:                 http://ivanjiang.com/blog
paginate:            1
baseurl:             
description:         'Welcome to my blog. '
comments:            true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ivan Jiang
  url:               http://ivanjiang.com
  email:             iplus26@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
